# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('file_format', models.CharField(max_length=16)),
                ('file_size', models.IntegerField(default=0)),
                ('base_url', models.URLField(max_length=1024)),
                ('url', models.URLField(max_length=1024)),
                ('image_url', models.URLField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('isbn', models.CharField(max_length=13)),
                ('publication_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='ebook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook.Livro'),
        ),
    ]
