# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0006_auto_20160725_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='download',
            field=models.IntegerField(default=0),
        ),
    ]
