# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0004_auto_20160725_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='isbn',
        ),
    ]
