# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0005_remove_livro_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='file_size',
        ),
        migrations.AlterField(
            model_name='ebook',
            name='file_format',
            field=models.SmallIntegerField(choices=[(1, 'PDF'), (2, 'MOBI'), (3, 'EPUB'), (4, 'HTML')], default=1),
        ),
    ]
